// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmlykvyagyjyccnunmqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbHlrdnlhZ3lqeWNjbnVubXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Nzc2MzQsImV4cCI6MjA2MzA1MzYzNH0.K7DYXnq3-AvbKBDDiImJeKfQWSNBmor_AabJ3aeTLj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);